site_name: ゼロから始めるゲノム解析（Python編） 
theme:
  name: material

plugins:
  - macros

extra_javascript:
  - javascripts/dcl-react.js.gz

markdown_extensions:
  - attr_list

extra:
  analytics:
    provider: google
    property: G-K627RX9W90